version: '3'
services:

  redis-service:
    image: 'redis:latest'
    container_name: rockwool-redis
    ports:
      - "6380:6379"
    restart: always
    networks:
      - my_network

networks:
  my_network:
    name: my_voucher_system_infra_network
    external: true